In [1]:
import cvxpy as cv
import numpy as np

In [2]:
def zero(n, i):
    zeros = np.zeros((1,n)).tolist()[0]
    zeros[i] = 1
    return zeros

def integer_solver(n, params, A, b, maximize = True, binary = False, integer = True):
    if not maximize:
        params = -params
    
    if binary:
        A = A.tolist()
        b = b.tolist()
        for i in range(n):
            A.append(zero(n, i))
            b.append([1])
        A = np.array(A)
        b = np.array(b)
    if integer:
        X = cv.Variable((n, 1), integer = True)
    else:
        X = cv.Variable((n, 1))
    obj = cv.Maximize(params @ X)
    rest = A@X <= b
    rest_0 = np.zeros((n,1))
    problem = cv.Problem(obj, [rest, X >= rest_0])
    if integer:
        problem.solve(solver = "GLPK_MI")
    else:
        problem.solve()
    try:
        return(problem.value, X.value.round(8))
    except:
        return(None, None)

# Nodo 0

In [3]:
integer_solver(4, np.array([[2, 4, 2, 3]]),
               np.array([[5, 4, 3, 7],
                         [1, 9, 5, 4],
                         [2, 10, 1, 2],
                         [1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1]]),
               np.array([[18], [21], [15], [1], [1], [1], [1]]),
               integer = False)

(10.599999999454283,
 array([[0.8],
        [1. ],
        [1. ],
        [1. ]]))

Dado que no hay elección entre variables, el árbol se bifurca como hijo izquierdo 1 se asume que la variable X1 toma el valor 0:

# Nodo 1

In [4]:
integer_solver(4, np.array([[2, 4, 2, 3]]),
               np.array([[5, 4, 3, 7],
                         [1, 9, 5, 4],
                         [2, 10, 1, 2],
                         [1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1],
                         [1, 0, 0, 0]]),
               np.array([[18], [21], [15], [1], [1], [1], [1], [0]]),
               integer = False)

(9.00000000121668,
 array([[0.],
        [1.],
        [1.],
        [1.]]))

Aquí termina la rama izquierda del nodo 0.

Continuamos con la rama derecha del nodo 0: asumiendo X1 = 1:

# Nodo 2

In [5]:
integer_solver(4, np.array([[2, 4, 2, 3]]),
               np.array([[5, 4, 3, 7],
                         [1, 9, 5, 4],
                         [2, 10, 1, 2],
                         [1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1],
                         [-1, 0, 0, 0]]),
               np.array([[18], [21], [15], [1], [1], [1], [1], [-1]]),
               integer = False)

(10.571428570271532,
 array([[1.        ],
        [1.        ],
        [1.        ],
        [0.85714286]]))

Luego, estando en el nodo 2, elegimos el nodo izquierdo, asumiendo X4 como 0:

# Nodo 5

In [6]:
integer_solver(4, np.array([[2, 4, 2, 3]]),
               np.array([[5, 4, 3, 7],
                         [1, 9, 5, 4],
                         [2, 10, 1, 2],
                         [1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1],
                         [-1, 0, 0, 0],
                         [0, 0, 0, 1]]),
               np.array([[18], [21], [15], [1], [1], [1], [1], [-1], [0]]),
               integer = False)

(8.000000002784002,
 array([[1.],
        [1.],
        [1.],
        [0.]]))

Aquí termina la rama izquierda del 2.

Continuamos con el nodo derecho del 2, asumiendo X4 como 1:

# Nodo 6

In [7]:
integer_solver(4, np.array([[2, 4, 2, 3]]),
               np.array([[5, 4, 3, 7],
                         [1, 9, 5, 4],
                         [2, 10, 1, 2],
                         [1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1],
                         [-1, 0, 0, 0],
                         [0, 0, 0, -1]]),
               np.array([[18], [21], [15], [1], [1], [1], [1], [-1], [-1]]),
               integer = False)

(10.333333333436979,
 array([[1.        ],
        [1.        ],
        [0.66666667],
        [1.        ]]))

Desde este nodo tenemos un hijo izquierdo asumiendo que X3 vale 0:

# Nodo 13

In [8]:
integer_solver(4, np.array([[2, 4, 2, 3]]),
               np.array([[5, 4, 3, 7],
                         [1, 9, 5, 4],
                         [2, 10, 1, 2],
                         [1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1],
                         [-1, 0, 0, 0],
                         [0, 0, 0, -1],
                         [0, 0, 1, 0]]),
               np.array([[18], [21], [15], [1], [1], [1], [1], [-1], [-1], [0]]),
               integer = False)

(9.000000003082146,
 array([[1.],
        [1.],
        [0.],
        [1.]]))

Hasta aquí termina la rama izquierda del nodo 6

Ahora vemos si X3 toma el valor de 1:

# Nodo 14

In [9]:
integer_solver(4, np.array([[2, 4, 2, 3]]),
               np.array([[5, 4, 3, 7],
                         [1, 9, 5, 4],
                         [2, 10, 1, 2],
                         [1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1],
                         [-1, 0, 0, 0],
                         [0, 0, 0, -1],
                         [0, 0, -1, 0]]),
               np.array([[18], [21], [15], [1], [1], [1], [1], [-1], [-1], [-1]]),
               integer = False)

(10.000000002155154,
 array([[1.  ],
        [0.75],
        [1.  ],
        [1.  ]]))

Aquí obtenemos su rama izquierda cuando X2 vale 0:

# Nodo 29

In [10]:
integer_solver(4, np.array([[2, 4, 2, 3]]),
               np.array([[5, 4, 3, 7],
                         [1, 9, 5, 4],
                         [2, 10, 1, 2],
                         [1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1],
                         [-1, 0, 0, 0],
                         [0, 0, 0, -1],
                         [0, 0, -1, 0], 
                         [0, 1, 0, 0]]),
               np.array([[18], [21], [15], [1], [1], [1], [1], [-1], [-1], [-1], [0]]),
               integer = False)

(7.0000000031424126,
 array([[1.],
        [0.],
        [1.],
        [1.]]))

Aquí termina la rama izquierda del nodo 14. Probamos la rama derecha tomando X2 como 1:

# Nodo 30

In [11]:
integer_solver(4, np.array([[2, 4, 2, 3]]),
               np.array([[5, 4, 3, 7],
                         [1, 9, 5, 4],
                         [2, 10, 1, 2],
                         [1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1],
                         [-1, 0, 0, 0],
                         [0, 0, 0, -1],
                         [0, 0, -1, 0], 
                         [0, -1, 0, 0]]),
               np.array([[18], [21], [15], [1], [1], [1], [1], [-1], [-1], [-1], [-1]]),
               integer = False)

(None, None)

Aquí no habría solución.